/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AgentMetadata,
    AgentMetadataFromJSON,
    AgentMetadataToJSON,
    ServerServerError,
    ServerServerErrorFromJSON,
    ServerServerErrorToJSON,
} from '../models';

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * Get Agents
     * Get Agents
     */
    async agentsGetRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<AgentMetadata>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/agents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentMetadataFromJSON));
    }

    /**
     * Get Agents
     * Get Agents
     */
    async agentsGet(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<AgentMetadata>> {
        const response = await this.agentsGetRaw(initOverrides);
        return await response.value();
    }

}
