/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CaptureKpture,
    CaptureKptureFromJSON,
    CaptureKptureToJSON,
    ServerKptureRequest,
    ServerKptureRequestFromJSON,
    ServerKptureRequestToJSON,
    ServerServerError,
    ServerServerErrorFromJSON,
    ServerServerErrorToJSON,
} from '../models';

export interface ApiV1KpturePostRequest {
    data: ServerKptureRequest;
}

export interface ApiV1KptureUuidDownloadGetRequest {
    uuid: string;
}

export interface ApiV1KptureUuidGetRequest {
    uuid: string;
}

export interface ApiV1KptureUuidStopPutRequest {
    uuid: string;
}

/**
 * 
 */
export class KpturesApi extends runtime.BaseAPI {

    /**
     * Start Kpture
     * Start Kpture
     */
    async apiV1KpturePostRaw(requestParameters: ApiV1KpturePostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<CaptureKpture>> {
        if (requestParameters.data === null || requestParameters.data === undefined) {
            throw new runtime.RequiredError('data','Required parameter requestParameters.data was null or undefined when calling apiV1KpturePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/kpture`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServerKptureRequestToJSON(requestParameters.data),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CaptureKptureFromJSON(jsonValue));
    }

    /**
     * Start Kpture
     * Start Kpture
     */
    async apiV1KpturePost(requestParameters: ApiV1KpturePostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<CaptureKpture> {
        const response = await this.apiV1KpturePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download kpture
     * Download kpture
     */
    async apiV1KptureUuidDownloadGetRaw(requestParameters: ApiV1KptureUuidDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling apiV1KptureUuidDownloadGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/kpture/{uuid}/download`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download kpture
     * Download kpture
     */
    async apiV1KptureUuidDownloadGet(requestParameters: ApiV1KptureUuidDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.apiV1KptureUuidDownloadGetRaw(requestParameters, initOverrides);
    }

    /**
     * Get kapture
     * Get kapture
     */
    async apiV1KptureUuidGetRaw(requestParameters: ApiV1KptureUuidGetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<CaptureKpture>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling apiV1KptureUuidGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/kpture/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CaptureKptureFromJSON(jsonValue));
    }

    /**
     * Get kapture
     * Get kapture
     */
    async apiV1KptureUuidGet(requestParameters: ApiV1KptureUuidGetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<CaptureKpture> {
        const response = await this.apiV1KptureUuidGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop Kpture
     * Stop Kpture
     */
    async apiV1KptureUuidStopPutRaw(requestParameters: ApiV1KptureUuidStopPutRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<CaptureKpture>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling apiV1KptureUuidStopPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/kpture/{uuid}/stop`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CaptureKptureFromJSON(jsonValue));
    }

    /**
     * Stop Kpture
     * Stop Kpture
     */
    async apiV1KptureUuidStopPut(requestParameters: ApiV1KptureUuidStopPutRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<CaptureKpture> {
        const response = await this.apiV1KptureUuidStopPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get kaptures
     * Get kaptures
     */
    async apiV1KpturesGetRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<{ [key: string]: CaptureKpture; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/kptures`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, CaptureKptureFromJSON));
    }

    /**
     * Get kaptures
     * Get kaptures
     */
    async apiV1KpturesGet(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<{ [key: string]: CaptureKpture; }> {
        const response = await this.apiV1KpturesGetRaw(initOverrides);
        return await response.value();
    }

}
