/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CaptureKpture,
    CaptureKptureFromJSON,
    CaptureKptureToJSON,
    ServerKptureNamespaceRequest,
    ServerKptureNamespaceRequestFromJSON,
    ServerKptureNamespaceRequestToJSON,
    ServerServerError,
    ServerServerErrorFromJSON,
    ServerServerErrorToJSON,
} from '../models';

export interface K8sNamespacesNamespaceInjectPostRequest {
    namespace: string;
}

export interface KptureK8sNamespacePostRequest {
    data: ServerKptureNamespaceRequest;
}

/**
 * 
 */
export class KubernetesApi extends runtime.BaseAPI {

    /**
     * Get all kubernetes namespaces
     * Get all kubernetes namespaces
     */
    async k8sNamespacesGetRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/k8s/namespaces`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all kubernetes namespaces
     * Get all kubernetes namespaces
     */
    async k8sNamespacesGet(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<string>> {
        const response = await this.k8sNamespacesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Inject annotation webhook
     * Inject annotation webhook
     */
    async k8sNamespacesNamespaceInjectPostRaw(requestParameters: K8sNamespacesNamespaceInjectPostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.namespace === null || requestParameters.namespace === undefined) {
            throw new runtime.RequiredError('namespace','Required parameter requestParameters.namespace was null or undefined when calling k8sNamespacesNamespaceInjectPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/k8s/namespaces/{namespace}/inject`.replace(`{${"namespace"}}`, encodeURIComponent(String(requestParameters.namespace))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Inject annotation webhook
     * Inject annotation webhook
     */
    async k8sNamespacesNamespaceInjectPost(requestParameters: K8sNamespacesNamespaceInjectPostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.k8sNamespacesNamespaceInjectPostRaw(requestParameters, initOverrides);
    }

    /**
     * Start namespace kpture
     * Start namespace kpture
     */
    async kptureK8sNamespacePostRaw(requestParameters: KptureK8sNamespacePostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<CaptureKpture>> {
        if (requestParameters.data === null || requestParameters.data === undefined) {
            throw new runtime.RequiredError('data','Required parameter requestParameters.data was null or undefined when calling kptureK8sNamespacePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/kpture/k8s/namespace`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServerKptureNamespaceRequestToJSON(requestParameters.data),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CaptureKptureFromJSON(jsonValue));
    }

    /**
     * Start namespace kpture
     * Start namespace kpture
     */
    async kptureK8sNamespacePost(requestParameters: KptureK8sNamespacePostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<CaptureKpture> {
        const response = await this.kptureK8sNamespacePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get enabled kubernetes namespaces
     * Get enabled kubernetes namespaces
     */
    async kptureK8sNamespacesGetRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/kpture/k8s/namespaces`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get enabled kubernetes namespaces
     * Get enabled kubernetes namespaces
     */
    async kptureK8sNamespacesGet(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<string>> {
        const response = await this.kptureK8sNamespacesGetRaw(initOverrides);
        return await response.value();
    }

}
