/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ServerServerError,
    ServerServerErrorFromJSON,
    ServerServerErrorToJSON,
} from '../models';

export interface ApiV1ProfileProfileNamePostRequest {
    profileName: string;
}

/**
 * 
 */
export class ProfilesApi extends runtime.BaseAPI {

    /**
     * Create profile
     * Create profile
     */
    async apiV1ProfileProfileNamePostRaw(requestParameters: ApiV1ProfileProfileNamePostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.profileName === null || requestParameters.profileName === undefined) {
            throw new runtime.RequiredError('profileName','Required parameter requestParameters.profileName was null or undefined when calling apiV1ProfileProfileNamePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/profile/{profileName}`.replace(`{${"profileName"}}`, encodeURIComponent(String(requestParameters.profileName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create profile
     * Create profile
     */
    async apiV1ProfileProfileNamePost(requestParameters: ApiV1ProfileProfileNamePostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.apiV1ProfileProfileNamePostRaw(requestParameters, initOverrides);
    }

    /**
     * Get profiles
     * Get profiles
     */
    async apiV1ProfilesGetRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/profiles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get profiles
     * Get profiles
     */
    async apiV1ProfilesGet(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<string>> {
        const response = await this.apiV1ProfilesGetRaw(initOverrides);
        return await response.value();
    }

}
