/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ServerServerError,
    ServerServerErrorFromJSON,
    ServerServerErrorToJSON,
} from '../models';

export interface ProfileProfileNameDeleteRequest {
    profileName: string;
}

export interface ProfileProfileNamePostRequest {
    profileName: string;
}

/**
 * 
 */
export class ProfilesApi extends runtime.BaseAPI {

    /**
     * Delete profile
     * Delete profile
     */
    async profileProfileNameDeleteRaw(requestParameters: ProfileProfileNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.profileName === null || requestParameters.profileName === undefined) {
            throw new runtime.RequiredError('profileName','Required parameter requestParameters.profileName was null or undefined when calling profileProfileNameDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/profile/{profileName}`.replace(`{${"profileName"}}`, encodeURIComponent(String(requestParameters.profileName))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete profile
     * Delete profile
     */
    async profileProfileNameDelete(requestParameters: ProfileProfileNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.profileProfileNameDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Create profile
     * Create profile
     */
    async profileProfileNamePostRaw(requestParameters: ProfileProfileNamePostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.profileName === null || requestParameters.profileName === undefined) {
            throw new runtime.RequiredError('profileName','Required parameter requestParameters.profileName was null or undefined when calling profileProfileNamePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/profile/{profileName}`.replace(`{${"profileName"}}`, encodeURIComponent(String(requestParameters.profileName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create profile
     * Create profile
     */
    async profileProfileNamePost(requestParameters: ProfileProfileNamePostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.profileProfileNamePostRaw(requestParameters, initOverrides);
    }

    /**
     * Get profiles
     * Get profiles
     */
    async profilesGetRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/profiles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get profiles
     * Get profiles
     */
    async profilesGet(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<string>> {
        const response = await this.profilesGetRaw(initOverrides);
        return await response.value();
    }

}
