/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ServerServerError,
    ServerServerErrorFromJSON,
    ServerServerErrorToJSON,
} from '../models';

/**
 * 
 */
export class WiresharkApi extends runtime.BaseAPI {

    /**
     * Get hostfile
     * Get hostfile
     */
    async apiV1WiresharkHostfileGetRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/wireshark/hostfile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Get hostfile
     * Get hostfile
     */
    async apiV1WiresharkHostfileGet(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<string> {
        const response = await this.apiV1WiresharkHostfileGetRaw(initOverrides);
        return await response.value();
    }

}
