
name: Create Release
on: [workflow_dispatch]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Bump version and push tag
        id: bumptagfake
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: "main"
          DRY_RUN: "true"
          DEFAULT_BUMP : "patch"
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/kpture/:${{ steps.bumptagfake.outputs.new_tag }}"
  release:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: azure/setup-helm@v3
      - name: set repository safe
        run : git config --global --add safe.directory /github/workspace
      - name: create next tag
        id: bumptagfake
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: "main"
          DRY_RUN: "true"
          DEFAULT_BUMP : "patch"
      - name: Create TAG
        id: bumptag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: "main"
          DEFAULT_BUMP : "patch"
      - name: Release Changelog Builder
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bumptag.outputs.new_tag }}
          release_name: Release ${{ steps.bumptag.outputs.new_tag }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false