/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgentInfo,
    AgentInfoFromJSON,
    AgentInfoFromJSONTyped,
    AgentInfoToJSON,
} from './AgentInfo';
import {
    CaptureInfo,
    CaptureInfoFromJSON,
    CaptureInfoFromJSONTyped,
    CaptureInfoToJSON,
} from './CaptureInfo';

/**
 * 
 * @export
 * @interface CaptureKpture
 */
export interface CaptureKpture {
    /**
     * 
     * @type {Array<AgentInfo>}
     * @memberof CaptureKpture
     */
    agents?: Array<AgentInfo>;
    /**
     * 
     * @type {CaptureInfo}
     * @memberof CaptureKpture
     */
    captureInfo?: CaptureInfo;
    /**
     * 
     * @type {string}
     * @memberof CaptureKpture
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CaptureKpture
     */
    profilName?: string;
    /**
     * 
     * @type {string}
     * @memberof CaptureKpture
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof CaptureKpture
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CaptureKpture
     */
    stopTime?: string;
    /**
     * 
     * @type {string}
     * @memberof CaptureKpture
     */
    uuid?: string;
}

export function CaptureKptureFromJSON(json: any): CaptureKpture {
    return CaptureKptureFromJSONTyped(json, false);
}

export function CaptureKptureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptureKpture {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agents': !exists(json, 'agents') ? undefined : ((json['agents'] as Array<any>).map(AgentInfoFromJSON)),
        'captureInfo': !exists(json, 'captureInfo') ? undefined : CaptureInfoFromJSON(json['captureInfo']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'profilName': !exists(json, 'profilName') ? undefined : json['profilName'],
        'startTime': !exists(json, 'startTime') ? undefined : json['startTime'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'stopTime': !exists(json, 'stopTime') ? undefined : json['stopTime'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}

export function CaptureKptureToJSON(value?: CaptureKpture | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agents': value.agents === undefined ? undefined : ((value.agents as Array<any>).map(AgentInfoToJSON)),
        'captureInfo': CaptureInfoToJSON(value.captureInfo),
        'name': value.name,
        'profilName': value.profilName,
        'startTime': value.startTime,
        'status': value.status,
        'stopTime': value.stopTime,
        'uuid': value.uuid,
    };
}

