/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerKptureNamespaceRequest
 */
export interface ServerKptureNamespaceRequest {
    /**
     * 
     * @type {string}
     * @memberof ServerKptureNamespaceRequest
     */
    kptureName?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerKptureNamespaceRequest
     */
    kptureNamespace?: string;
}

export function ServerKptureNamespaceRequestFromJSON(json: any): ServerKptureNamespaceRequest {
    return ServerKptureNamespaceRequestFromJSONTyped(json, false);
}

export function ServerKptureNamespaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerKptureNamespaceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kptureName': !exists(json, 'kptureName') ? undefined : json['kptureName'],
        'kptureNamespace': !exists(json, 'kptureNamespace') ? undefined : json['kptureNamespace'],
    };
}

export function ServerKptureNamespaceRequestToJSON(value?: ServerKptureNamespaceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kptureName': value.kptureName,
        'kptureNamespace': value.kptureNamespace,
    };
}

