/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerServerError
 */
export interface ServerServerError {
    /**
     * 
     * @type {string}
     * @memberof ServerServerError
     */
    message?: string;
}

export function ServerServerErrorFromJSON(json: any): ServerServerError {
    return ServerServerErrorFromJSONTyped(json, false);
}

export function ServerServerErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerServerError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ServerServerErrorToJSON(value?: ServerServerError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

