/* tslint:disable */
/* eslint-disable */
/**
 * Kpture-backend
 * Kpture Backend server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: kpture.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ServerKptureRequestAgentsRequestInner,
    ServerKptureRequestAgentsRequestInnerFromJSON,
    ServerKptureRequestAgentsRequestInnerFromJSONTyped,
    ServerKptureRequestAgentsRequestInnerToJSON,
} from './ServerKptureRequestAgentsRequestInner';

/**
 * 
 * @export
 * @interface ServerKptureRequest
 */
export interface ServerKptureRequest {
    /**
     * 
     * @type {Array<ServerKptureRequestAgentsRequestInner>}
     * @memberof ServerKptureRequest
     */
    agentsRequest?: Array<ServerKptureRequestAgentsRequestInner>;
    /**
     * 
     * @type {string}
     * @memberof ServerKptureRequest
     */
    kptureName?: string;
}

export function ServerKptureRequestFromJSON(json: any): ServerKptureRequest {
    return ServerKptureRequestFromJSONTyped(json, false);
}

export function ServerKptureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerKptureRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agentsRequest': !exists(json, 'agentsRequest') ? undefined : ((json['agentsRequest'] as Array<any>).map(ServerKptureRequestAgentsRequestInnerFromJSON)),
        'kptureName': !exists(json, 'kptureName') ? undefined : json['kptureName'],
    };
}

export function ServerKptureRequestToJSON(value?: ServerKptureRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agentsRequest': value.agentsRequest === undefined ? undefined : ((value.agentsRequest as Array<any>).map(ServerKptureRequestAgentsRequestInnerToJSON)),
        'kptureName': value.kptureName,
    };
}

